# Generated by Django 5.2 on 2025-04-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.JSONField()),
                ('smtp', models.JSONField()),
                ('ldap', models.JSONField()),
            ],
        ),
    ]
