# Generated by Django 5.2 on 2025-04-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='ldap',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='proxy',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='smtp',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
