# Generated by Django 5.2 on 2025-04-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_scan_scan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='id',
        ),
        migrations.AddField(
            model_name='scan',
            name='project_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
