# Generated by Django 5.2 on 2025-04-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_project_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='id',
        ),
        migrations.AddField(
            model_name='scan',
            name='scan_id',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
