# Generated by Django 5.2 on 2025-05-06 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('project_author', models.CharField(max_length=255)),
                ('trash', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('scan_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('scan_name', models.CharField(max_length=255)),
                ('scan_author', models.CharField(max_length=255)),
                ('scan_status', models.CharField(max_length=50)),
                ('trash', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='scan.project')),
            ],
        ),
    ]
