# Generated by Django 5.2 on 2025-04-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('scan_name', models.CharField(max_length=255)),
                ('scan_id', models.CharField(max_length=100, unique=True)),
                ('tools_name', models.CharField(max_length=255)),
                ('scan_author', models.CharField(max_length=255)),
                ('scan_config_file_path', models.TextField()),
                ('result_file_path', models.TextField()),
                ('scan_status', models.CharField(max_length=50)),
                ('trash', models.BooleanField(default=False)),
            ],
        ),
    ]
