# Generated by Django 5.2 on 2025-04-25 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('project_author', models.CharField(max_length=255)),
                ('trash', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='scan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='result_file_path',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='scan_config_file_path',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='tools_name',
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='scan',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='scan.project'),
            preserve_default=False,
        ),
    ]
